/**:
  ros__parameters:
    wheel_radius: 0.033
    track_width: 0.16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 0.024 # This is flipped. It should really be rad/sec per motor cmd
    encoder_ticks_per_rad: 651.0 # (2 ^ 12) / (2 * pi)

    collision_radius: 0.11
    wheel_left: "wheel_left_joint"
    wheel_right: "wheel_right_joint"