/**:
  ros__parameters:
    wheel_radius: 0.033
    track_width: 0.16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad: 2e12
    collision_radius: 0.11
    wheel_left: "wheel_left_joint"
    wheel_right: "wheel_right_joint"