/**:
  ros__parameters:
    # x0: -0.5
    # y0: 0.7
    # theta0: 1.28
    x0: 0.00001
    y0: 0.000001
    theta0: 0.0000001
    obstacles/x: [-0.5, 0.8, 0.4]
    obstacles/y: [-0.7, -0.8, 0.8]
    obstacles/r: 0.038